export  const ActionType={

    USER_INFO:'USER_INFO',

    // common
    SET_LOADING_TOGGLE:'SET_LOADING_TOGGLE',  //设置 loading 显示状态
    COMMON_MODAL_VISIBLE:'COMMON_MODAL_VISIBLE',

    // versionLog
    VERSION_LOG_TOGGLE:'VERSION_LOG_TOGGLE',  //版本库是否显示
    VERSION_LOG_FETCH_RECEIVE:'VERSION_LOG_FETCH_RECEIVE',
    VERSION_HANDLED_DATA:'VERSION_HANDLED_DATA',
    // VERSION_LOG_CURRENT_V_INFO:'VERSION_LOG_CURRENT_V_INFO',

    // asideNav
    ASIDE_NAV_ACTION:'ASIDE_NAV_ACTION',      //左侧导航 当前选中
    ASIDE_NAV_NAME:'ASIDE_NAV_NAME',

    // main
    DOC_COUNT:'DOC_COUNT',
    RESOLVE_ICD10S_LIST:'RESOLVE_ICD10S_LIST',
    CURRENT_DOC_PUBLISHED:'CURRENT_DOC_PUBLISHED',
    MAIN_TAB_ACTION:'MAIN_TAB_ACTION',    //main tab栏 当前选中
    MAIN_TABLE_TR_ACTION:'MAIN_TABLE_TR_ACTION',  // main 已发布和全部 当前选中项

    MAIN_OVERVIEW_FETCH_RECEIVE:'MAIN_OVERVIEW_FETCH_RECEIVE',    //overview fetch receive
    MAIN_OVERVIEW_FETCH_INVALIDATE:'MAIN_OVERVIEW_FETCH_INVALIDATE',    //overview fetch 失效（超时）

    MAIN_RELEASED_FETCH_RECEIVE:'MAIN_RELEASED_FETCH_RECEIVE',    //released fetch receive
    MAIN_RELEASED_FETCH_INVALIDATE:'MAIN_RELEASED_FETCH_INVALIDATE',    //overview fetch 失效（超时）
    MAIN_RELEASED_CURRENTPAGE:'MAIN_RELEASED_CURRENTPAGE',

    MAIN_All_FETCH_RECEIVE:'MAIN_All_FETCH_RECEIVE',    //all fetch receive
    MAIN_ALL_INVALIDATE:'MAIN_ALL_FETCH_INVALIDATE',    //overview fetch 失效（超时）
    MAIN_All_CURRENTPAGE:'MAIN_All_CURRENTPAGE',

    // detail
    DETAIL_TAB_ACTION:'DETAIL_TAB_ACTION',    // 详情页 tab 当前选中状态
    DETAIL_PUBLISH_STATE:'DETAIL_PUBLISH_STATE',

    DETAIL_NORMAL_FETCH_RECEIVE:'DETAIL_NORMAL_FETCH_RECEIVE',      // 标准
    DETAIL_NORMAL_HANDLED_DATA:'DETAIL_NORMAL_HANDLED_DATA',      //处理后台数据后的结果数据

    DETAIL_ENCYCLOPEDIA_FETCH_RECEIVE:'DETAIL_ENCYCLOPEDIA_FETCH_RECEIVE',      //百科
    DETAIL_ENCY_HANDLED_DATA:'DETAIL_ENCY_HANDLED_DATA',

    DETAIL_SYNONYMS_FETCH_RECEIVE:'DETAIL_SYNONYMS_FETCH_RECEIVE',      //同义词
    DETAIL_SYNONYMS_HANDLED_DATA:'DETAIL_SYNONYMS_HANDLED_DATA',

    DETAIL_HANDLE_DEPARTMENT:'DETAIL_HANDLE_DEPARTMENT',

    // edit
    EDIT_NORMAL_INIT:'EDIT_NORMAL_INIT',   //edit normal page init data
    EDIT_NORMAL_TYPE:'EDIT_NORMAL_TYPE',
    EDIT_NORMAL_DATA:'EDIT_NORMAL_DATA',  //将处理好的数据放到 editNormalData state
    EDIT_NORMAL_ID_CHANGE:'EDIT_NORMAL_ID_CHANGE',
    EDIT_NORMAL_NAME_CHANGE:'EDIT_NORMAL_NAME_CHANGE',
    EDIT_NORMAL_FRIENDLYNAME_CHANGE:'EDIT_NORMAL_FRIENDLYNAME_CHANGE',
    EDIT_NORMAL_SHORTNAME_CHANGE:'EDIT_NORMAL_SHORTNAME_CHANGE',
    EDIT_NORMAL_GENDER_CHANGE:'EDIT_NORMAL_GENDER_CHANGE',
    EDIT_NORMAL_AGE_CHANGE:'EDIT_NORMAL_AGE_CHANGE',
    EDIT_NORMAL_OFFICE_CHANGE:'EDIT_NORMAL_OFFICE_CHANGE',
    EDIT_NORMAL_ICD_ADD:'EDIT_NORMAL_ICD_ADD',
    EDIT_NORMAL_ICD_DELETE:'EDIT_NORMAL_ICD_DELETE',
    EDIT_NORMAL_ICD_SELECT_CHANGE:'EDIT_NORMAL_ICD_SELECT_CHANGE',
    EDIT_NORMAL_ICD_INPUT_CHANGE:'EDIT_NORMAL_ICD_INPUT_CHANGE',

    EDIT_FOOTER_INIT:'EDIT_FOOTER_INIT',
    EDIT_FOOTER_COMMIT:'EDIT_FOOTER_COMMIT',
    EDIT_FOOTER_APPROVE:'EDIT_FOOTER_APPROVE',
    EDIT_FOOTER_SETCURRENT:'EDIT_FOOTER_SETCURRENT',
    EDIT_SET_STATE_APPROVE:'EDIT_SET_STATE_APPROVE',
    EDIT_SET_STATE_SETCURRENT:"EDIT_SET_STATE_SETCURRENT",

    EDIT_ENCY_INIT:'EDIT_ENCY_INIT',
    EDIT_ENCY_INPUT_VALUE:'EDIT_ENCY_INPUT_VALUE',

    EDIT_SYNONYMS_INIT:'EDIT_SYNONYMS_INIT',
    EDIT_SYNONYMS_ADD:'EDIT_SYNONYMS_ADD',
    EDIT_SYNONYMS_EDIT:'EDIT_SYNONYMS_EDIT',
    EDIT_SYNONYMS_DELETE:'EDIT_SYNONYMS_DELETE',
    EDIT_SYNONYMS_MODAL_INPUT:'EDIT_SYNONYMS_MODAL_INPUT',

    EDIT_HANDLE_DEPARTMENT:'EDIT_HANDLE_DEPARTMENT',
    EDIT_DELETE_DEPARTMENT:'EDIT_DELETE_DEPARTMENT',

    // admin
    ADMIN_TAB_ACTION:'ADMIN_TAB_ACTION',   //admin tab栏 当前选中
    ADMIN_TOTAL_ACTION:'ADMIN_TOTAL_ACTION',
    ADMIN_TYPE_ACTION:'ADMIN_TYPE_ACTION',
    ADMIN_STATS_FETCH:'ADMIN_STATS_FETCH',
    ADMIN_TABLE_FETCH:'ADMIN_TABLE_FETCH',

    // structured
    STRUCTURED_CURRENT_TAB:"STRUCTURED_CURRENT_TAB",
    STRUCTURED_EDIT_INP_VAL:'STRUCTURED_EDIT_INP_VAL',
    STRUCTURED_EDIT_CUTRESULT_CHANGE:'STRUCTURED_EDIT_CUTRESULT_CHANGE',
    STRUCTURED_HANDLED_FETCHDATA:'STRUCTURED_HANDLED_FETCHDATA',
    STRUCTURED_FETCH_RECIVE:'STRUCTURED_FETCH_RECIVE',

    // symptom
    SYMPTOM_EDIT_NORMAL_METADATA:'SYMPTOM_EDIT_NORMAL_METADATA',
    SYMPTOM_EDIT_NORMAL_NAME:'SYMPTOM_EDIT_NORMAL_NAME',
    SYMPTOM_EDIT_NORMAL_KEY:'SYMPTOM_EDIT_NORMAL_KEY',
    SYMPTOM_EDIT_NORMAL_GENDER:'SYMPTOM_EDIT_NORMAL_GENDER',
    SYMPTOM_EDIT_NORMAL_AGERANGE:'SYMPTOM_EDIT_NORMAL_AGERANGE',
    SYMPTOM_EDIT_NORMAL_CATEGORIES:'SYMPTOM_EDIT_NORMAL_CATEGORIES',
    SYMPTOM_EDIT_NORMAL_ADD_ATTRSVALUES:'SYMPTOM_EDIT_NORMAL_ADD_ATTRSVALUES',
    SYMPTOM_EDIT_NORMAL_ADD_ATTRS:'SYMPTOM_EDIT_NORMAL_ADD_ATTRS',
    SYMPTOM_EDIT_NORMAL_REMOVE_ATTRS:'SYMPTOM_EDIT_NORMAL_REMOVE_ATTRS',
    SYMPTOM_EDIT_NORMAL_REMOVE_ATTRSVALUES:'SYMPTOM_EDIT_NORMAL_REMOVE_ATTRSVALUES',
    SYMPTOM_EDIT_NORMAL_DELETE_CATEGORIES:'SYMPTOM_EDIT_NORMAL_DELETE_CATEGORIES',
    SYMPTOM_EDIT_NORMAL_ADD_CATEGORIES:'SYMPTOM_EDIT_NORMAL_ADD_CATEGORIES',
    SYMPTOM_EDIT_NORMAL_SET_COMMON:'SYMPTOM_EDIT_NORMAL_SET_COMMON',

    // labitem
    LABITEM_EDIT_NORMAL_CATEGORIES:'LABITEM_EDIT_NORMAL_CATEGORIES',
    LABITEM_EDIT_NORMAL_INPVAL:'LABITEM_EDIT_NORMAL_INPVAL'
}
